image: registry.gitlab.com/jkcclemens/msyt/build:latest

stages:
  - build
  # - test
  - build_release

build_linux:
  stage: build
  script: cargo build --all-features

build_linux_release:
  stage: build_release
  script: cargo build --all-features --release

build_win:
  stage: build
  script: cargo build --all-features --target=x86_64-pc-windows-gnu

build_win_release:
  stage: build_release
  script: cargo build --all-features --release --target=x86_64-pc-windows-gnu

build_linux_musl:
  stage: build
  script: cargo build --all-features --target=x86_64-unknown-linux-musl

build_linux_musl_release:
  stage: build_release
  script: cargo build --all-features --release --target=x86_64-unknown-linux-musl
