image: registry.gitlab.com/jkcclemens/msyt/build:latest

stages:
  - build
  # - test
  - release

build_linux:
  stage: build
  script: cargo build --all-features

build_linux_release:
  stage: release
  script: cargo build --all-features --release
  artifacts:
    paths:
      - target/release/msyt

build_win:
  stage: build
  script: cargo build --all-features --target=x86_64-pc-windows-gnu

build_win_release:
  stage: release
  script: cargo build --all-features --release --target=x86_64-pc-windows-gnu
  artifacts:
    paths:
      - target/x86_64-pc-windows-gnu/release/msyt.exe

build_linux_musl:
  stage: build
  script: cargo build --all-features --target=x86_64-unknown-linux-musl

build_linux_musl_release:
  stage: release
  script: cargo build --all-features --release --target=x86_64-unknown-linux-musl
  artifacts:
    paths:
      - target/x86_64-unknown-linux-musl/release/msyt
